name: AD tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1'
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
        AD:
          - Enzyme
          - ForwardDiff
          - Tapir
          - Tracker
          - ReverseDiff
          - Zygote
        exclude:
          - version: 1.6
            AD: Tapir
          # TODO(mhauru) Hopefully can enable Enzyme on older versions at some point, see
          # discussion in https://github.com/TuringLang/Bijectors.jl/pull.
          - version: 1.6
            AD: Enzyme
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        env:
          GROUP: AD
          AD: ${{ matrix.AD }}
